// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/registros": {
    params: {};
  };
  "/pacientes": {
    params: {};
  };
  "/metas": {
    params: {};
  };
  "/auditoria": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/registros" | "/pacientes" | "/metas" | "/auditoria";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/dashboard" | "/registros" | "/pacientes" | "/metas" | "/auditoria";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/dashboard-alias.tsx": {
    id: "routes/dashboard-alias";
    page: "/dashboard";
  };
  "routes/registros.tsx": {
    id: "routes/registros";
    page: "/registros";
  };
  "routes/pacientes.tsx": {
    id: "routes/pacientes";
    page: "/pacientes";
  };
  "routes/metas.tsx": {
    id: "routes/metas";
    page: "/metas";
  };
  "routes/auditoria.tsx": {
    id: "routes/auditoria";
    page: "/auditoria";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard-alias": typeof import("./app/routes/dashboard-alias.tsx");
  "routes/registros": typeof import("./app/routes/registros.tsx");
  "routes/pacientes": typeof import("./app/routes/pacientes.tsx");
  "routes/metas": typeof import("./app/routes/metas.tsx");
  "routes/auditoria": typeof import("./app/routes/auditoria.tsx");
};